fix m instr in simulator
riscv-collab/v8 pull request #614
Opened 2022-05-29 15:13 UTC by usmnzain

This PR fixes issue #594

2022-05-30 00:42 UTC, luyahan requested changes

2022-05-30 00:42 UTC, luyahan commented on src/execution/riscv32/simulator-riscv32.h
> +inline uint64_t mulhu(uint32_t a, uint32_t b) {
return value need modify

2022-05-30 00:42 UTC, luyahan commented on src/execution/riscv32/simulator-riscv32.h
> +inline int64_t mulh(int32_t a, int32_t b) {
same

2022-05-30 14:38 UTC, usmnzain commented on src/execution/riscv32/simulator-riscv32.h
> +inline uint64_t mulhu(uint32_t a, uint32_t b) {
done

2022-05-31 01:38 UTC, luyahan approved these changes

2022-05-31 01:39 UTC, merged